repos:
  - repo: https://github.com/gitguardian/gg-shield
    rev: v1.5.0
    hooks:
      - id: ggshield
        language_version: python3
        stages: [commit]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: detect-aws-credentials
      - id: detect-private-key
  # - repo: git@github.com:Yelp/detect-secrets
  #   rev: v0.14.3
  #   hooks:
  #     - id: detect-secrets
  #       args: ['--baseline', '.secrets.baseline']
  #       exclude: .*/tests/.*
