version: '3.7'

services:
    tf:
        user: "1000:1000"
        image: hashicorp/terraform:1.0.0
        volumes:
            - .:/infra
        working_dir: /infra
        environment:
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}